apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "julianna.fullname" . }}
  labels:
    {{- include "julianna.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "julianna.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "julianna.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "julianna.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: pubuserfiles
            mountPath: "/var/www/html/public/userfiles"
          - name: userfiles
            mountPath: "/var/www/html/userfiles"
          env:
          - name: JULIANNA_ENV
            value: "production"
          - name: JULIANNA_APP_URL
            value: {{ required "app.url is required" .Values.app.url | quote }}
          - name: JULIANNA_SOURCE_URL
            value: {{ required "app.sourceUrl is required" .Values.app.sourceUrl | quote }}
          - name: JULIANNA_VERSION
            value: {{ (.Values.image.tag | default .Chart.AppVersion) | trimPrefix "v" | quote }}
          - name: JULIANNA_COMMIT
            value: {{ required "app.commit is required" .Values.app.commit | quote }}
          - name: JULIANNA_REGISTRATION_ENABLED
            value: {{ .Values.app.registrationEnabled | quote }}
          - name: JULIANNA_DB_HOST
            value: {{ printf "%s-mariadb" .Release.Name | quote }}
          - name: JULIANNA_SESSION_SECURE
            value: {{ .Values.app.session.secure | quote }}
          - name: JULIANNA_DB_USER
            value: {{ .Values.mariadb.auth.username | quote }}
          - name: JULIANNA_DB_PASSWORD
            value: {{ .Values.mariadb.auth.password | quote }}
          - name: JULIANNA_DB_DATABASE
            value: {{ .Values.mariadb.auth.database | quote }}
          - name: JULIANNA_SITENAME
            value: {{ .Values.app.sitename | quote }}
          - name: JULIANNA_LANGUAGE
            value: {{ .Values.app.language | quote }}
          - name: JULIANNA_DEFAULT_TIMEZONE
            value: {{ .Values.app.defaultTimezone | quote }}
          {{- if .Values.app.s3.enabled }}
          - name: JULIANNA_USE_S3
            value: {{ .Values.app.s3.enabled | quote }}
          - name: JULIANNA_S3_END_POINT
            value: {{ .Values.app.s3.endpoint | quote }}
          - name: JULIANNA_S3_KEY
            value: {{ .Values.app.s3.key | quote }}
          - name: JULIANNA_S3_SECRET
            value: {{ .Values.app.s3.secret | quote }}
          - name: JULIANNA_S3_BUCKET
            value: {{ .Values.app.s3.bucket | quote }}
          - name: JULIANNA_S3_USE_PATH_STYLE_ENDPOINT
            value: {{ .Values.app.s3.usePathStyleEndpoint | quote }}
          - name: JULIANNA_S3_REGION
            value: {{ .Values.app.s3.region | quote }}
          - name: JULIANNA_S3_FOLDER_NAME
            value: {{ .Values.app.s3.folderName | quote }}
          {{- end }}
          - name: JULIANNA_APP_KEY
            value: {{ required "app.session.password is required" .Values.app.session.password | quote }}
          - name: JULIANNA_SESSION_EXPIRATION
            value: {{ .Values.app.session.expiration | quote }}
          {{- if .Values.app.email.enabled }}
          - name: JULIANNA_EMAIL_USE_SMTP
            value: {{ .Values.app.email.enabled | quote }}
          - name: JULIANNA_EMAIL_RETURN
            value: {{ .Values.app.email.return | quote }}
          - name: JULIANNA_EMAIL_SMTP_HOSTS
            value: {{ .Values.app.email.smtp.hosts | quote }}
          - name: JULIANNA_EMAIL_SMTP_USERNAME
            value: {{ .Values.app.email.smtp.username | quote }}
          - name: JULIANNA_EMAIL_SMTP_PASSWORD
            value: {{ .Values.app.email.smtp.password | quote }}
          - name: JULIANNA_EMAIL_SMTP_AUTH
            value: {{ .Values.app.email.smtp.auth | quote }}
          - name: JULIANNA_EMAIL_SMTP_AUTO_TLS
            value: {{ .Values.app.email.smtp.autoTLS | quote }}
          - name: JULIANNA_EMAIL_SMTP_SECURE
            value: {{ .Values.app.email.smtp.secure | quote }}
          - name: JULIANNA_EMAIL_SMTP_PORT
            value: {{ .Values.app.email.smtp.port | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: pubuserfiles
        persistentVolumeClaim:
          claimName: {{ include "julianna.fullname" . }}-publicuserfiles
      - name: userfiles
        persistentVolumeClaim:
          claimName: {{ include "julianna.fullname" . }}-userfiles
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
