<style>
.agent-page{--agent-ink:#173744;--agent-muted:#55717b;--agent-line:#dbe7e7;--agent-tint:#f4faf8;color:var(--agent-ink)}
.agent-page .maincontentinner{max-width:1500px;padding-bottom:3rem}.agent-page h2{font-size:1.35rem;line-height:1.3;margin:.2rem 0 .75rem}.agent-page h3{font-size:1rem;margin:1.1rem 0 .45rem}.agent-page p{line-height:1.55}.agent-page a{color:#176779}.agent-page a:hover{text-decoration:underline}
.agent-hero{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(260px,.8fr);gap:2rem;align-items:center;padding:2rem 2.3rem;border-radius:1.2rem;background:linear-gradient(120deg,#edf8f3,#ecf6f8 60%,#fff4e8);border:1px solid #d8e9e4;margin-bottom:1.4rem}
.agent-hero h2{font-size:clamp(1.5rem,2vw,2rem);margin:.3rem 0}.agent-hero p{max-width:65ch;margin:.4rem 0}.agent-eyebrow{text-transform:uppercase;letter-spacing:.1em;font-size:.7rem;font-weight:800;color:#23816e}.agent-status{display:inline-flex;align-items:center;gap:.5rem;border-radius:999px;background:#fff;border:1px solid #dbe7e7;padding:.4rem .8rem;margin-top:.8rem;font-weight:700}.agent-status-dot{height:.55rem;width:.55rem;border-radius:50%;background:#9daeb2}.agent-status.is-active .agent-status-dot{background:#31a36e}.agent-status.is-paused .agent-status-dot{background:#e1a23b}.agent-status.is-unavailable .agent-status-dot{background:#ce6e6e}
.agent-hero-controls{display:flex;flex-direction:column;gap:.4rem}.agent-hero-controls label{font-weight:700}.agent-hero-controls select{width:100%;max-width:100%;padding:.62rem;border:1px solid #bfcecf;border-radius:.55rem;background:#fff}.agent-muted{color:var(--agent-muted);font-size:.9rem}.agent-setting-buttons{display:flex;flex-wrap:wrap;gap:.4rem;margin-top:.3rem}
.agent-whiteboard-link{font-weight:700;margin:.3rem 0}
.agent-main-grid{display:grid;grid-template-columns:minmax(0,1.7fr) minmax(270px,.8fr);gap:1rem;align-items:start}.agent-bottom-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem;margin-top:1rem}.agent-side-stack{display:grid;gap:1rem}.agent-card{background:#fff;border:1px solid var(--agent-line);border-radius:1rem;padding:1.25rem 1.4rem;box-shadow:0 4px 22px rgba(25,67,74,.045);min-width:0}.agent-card-heading{display:flex;align-items:start;justify-content:space-between;gap:.8rem;border-bottom:1px solid var(--agent-line);margin-bottom:.8rem}.agent-card-heading h2{margin:.2rem 0 .75rem}.agent-empty{color:var(--agent-muted);margin:.6rem 0}.agent-text-button{appearance:none;border:0;background:transparent;color:#176779;font-weight:700;cursor:pointer}.agent-text-button:hover{text-decoration:underline}
.agent-turns{min-height:235px;max-height:530px;overflow:auto;padding:.25rem 0 1rem;display:flex;flex-direction:column;gap:.8rem}.agent-turn{max-width:90%;padding:.8rem 1rem;border-radius:.8rem;background:var(--agent-tint);white-space:pre-wrap;overflow-wrap:anywhere}.agent-turn.is-user{margin-left:auto;background:#e8f1fa}.agent-turn strong{display:block;font-size:.8rem;margin-bottom:.2rem;color:#287266}.agent-turn.is-user strong{color:#466c9e}.agent-turn p{margin:0}.agent-compose textarea{width:100%;box-sizing:border-box;border:1px solid #c4d4d3;border-radius:.7rem;padding:.8rem;resize:vertical;min-height:85px}.agent-compose-footer{display:flex;align-items:center;justify-content:space-between;gap:1rem;margin-top:.55rem}.agent-compose-footer span{color:var(--agent-muted);font-size:.8rem}.agent-feedback{border-radius:.55rem;padding:.7rem;background:#fff2ef;color:#a24031}.agent-feedback.is-success{background:#eef8f1;color:#226a42}
.agent-conversation-actions{display:flex;gap:.5rem;align-items:center}.agent-conversation-actions select{max-width:180px;border:1px solid var(--agent-line);border-radius:.4rem;padding:.3rem;background:#fff}
.agent-list-item{border-top:1px solid var(--agent-line);padding:.75rem 0}.agent-list-item:first-child{border-top:0}.agent-list-item strong{display:block;overflow-wrap:anywhere}.agent-list-item p{margin:.3rem 0}.agent-list-item small{display:block;color:var(--agent-muted);font-size:.78rem}.agent-list-actions{display:flex;gap:.5rem;flex-wrap:wrap;margin-top:.55rem}.agent-list-actions button{font-size:.8rem}.agent-badge{display:inline-flex;border-radius:999px;padding:.15rem .55rem;background:#eaf3f4;color:#36656d;font-size:.76rem;font-weight:700}.agent-archive-link{text-align:right;margin:1.2rem 0}.agent-archive-intro{display:flex;justify-content:space-between;gap:1rem;align-items:center;margin:0 0 1rem}.agent-archive-intro p{margin:0}.agent-readonly{display:inline-flex;white-space:nowrap;color:#576a72;background:#e8efef;border-radius:999px;padding:.25rem .6rem;font-size:.75rem;font-weight:700}.agent-archive-grid{display:grid;grid-template-columns:minmax(0,1.4fr) minmax(280px,1fr);gap:1rem;align-items:start}.agent-archive-row{display:flex;justify-content:space-between;align-items:center;gap:1rem;border-top:1px solid var(--agent-line);padding:.85rem 0}.agent-archive-row:first-of-type{border-top:0}.agent-archive-row small{display:block;color:var(--agent-muted);margin-top:.25rem}.agent-archive-message{border-top:1px solid var(--agent-line);padding:.8rem 0}.agent-archive-message strong{margin-right:.7rem}.agent-archive-message small{color:var(--agent-muted)}.agent-archive-message p{white-space:pre-wrap;overflow-wrap:anywhere;margin:.35rem 0}.agent-archive-nodes{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:.6rem}.agent-archive-node{background:var(--agent-tint);border:1px solid var(--agent-line);border-radius:.6rem;padding:.7rem;overflow-wrap:anywhere}.agent-archive-node small{display:block;color:var(--agent-muted);text-transform:uppercase;font-size:.67rem}.agent-archive-node strong{display:block;margin:.2rem 0}.agent-archive-node p{margin:.3rem 0 0;white-space:pre-wrap}
.agent-draft-arguments{max-height:230px;overflow:auto;background:#f6f9f9;border-radius:.5rem;padding:.7rem;font-size:.78rem;white-space:pre-wrap;overflow-wrap:anywhere}
.agent-turn-body{white-space:normal;line-height:1.55;overflow-wrap:anywhere}.agent-turn.is-user .agent-turn-body{white-space:pre-wrap}.agent-turn-body p{margin:.45rem 0}.agent-turn-body p:first-child,.agent-turn-body .agent-turn-heading:first-child{margin-top:0}.agent-turn-body p:last-child,.agent-turn-body .agent-turn-list:last-child{margin-bottom:0}.agent-turn-body .agent-turn-heading{font-size:.95rem;line-height:1.35;margin:.75rem 0 .3rem;color:#245d61}.agent-turn-body .agent-turn-list{margin:.4rem 0 .6rem;padding-left:1.35rem}.agent-turn-body li{margin:.2rem 0}.agent-turn-body code{font-size:.9em;background:#e7efef;border-radius:.25rem;padding:.05rem .22rem}
@keyframes agent-complete{from{opacity:.6;transform:translateY(5px)}to{opacity:1;transform:translateY(0)}}.agent-feedback.is-success:not([hidden]){animation:agent-complete .3s ease-out}@media(prefers-reduced-motion:reduce){.agent-feedback.is-success:not([hidden]){animation:none}}
@media(max-width:950px){.agent-hero,.agent-main-grid,.agent-archive-grid{grid-template-columns:1fr}.agent-bottom-grid{grid-template-columns:1fr}}@media(max-width:600px){.agent-hero{padding:1.2rem}.agent-card{padding:1rem}.agent-compose-footer{align-items:flex-start;flex-direction:column}.agent-archive-intro{align-items:flex-start;flex-direction:column}}
</style>
